databricks_account_id      = "0c6d76dc-ee77-45f4-ac75-9a177cc435b4"
client_id                  = "a7c65ec9-faf2-432f-8512-2a32f798fd59"
client_secret              = "dose1426c5c499b1302abd8a68f3d5183695"
account_admin_group_name   = "account_admins"
workspace_user_group_name  = "workspace_users"
workspace_admin_group_name = "workspace_admins"
workspace_admins           = ["xa_admin1@pm.me", "xtarmitage+databricks-root@gmail.com"]
workspace_users            = ["xa_user1@pm.me", "xa_user2@pm.me", "xa_admin1@pm.me", "xtarmitage+databricks-root@gmail.com"]
account_admins             = ["xa_admin1@pm.me", "xtarmitage+databricks-root@gmail.com"]
databricks_account_owner_email = "xtarmitage+databricks-root@gmail.com"